apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: payment-orchestrator
  labels:
    app: orchestrator
    component: api
spec:
  type: ClusterIP
  selector:
    app: orchestrator
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None
